### ISSUE TITLE
Make container publicly accessible

### ISSUE THREAD

**Issue by oliverpool** [oliverpool/crossbuild-armhf#1]
@stapelberg somehow I don't have access to the `Package settings` to make the container image publicly accessible.

Can you change the package visibility to public ?
1. `Package settings` at the bottom right of https://github.com/gokrazy-community/crossbuild-armhf/pkgs/container/crossbuild-armhf
2. At the very bottom, `Danger Zone` > `Change package visibility` > `Public`

Thank you!

**Comment by oliverpool** [comment]
(I see that I don't have admin rights on the community, this is probably why I don't have admin rights on this repo as well)

**Comment by stapelberg** [comment]
Package visibility set to public
